Polygonum aviculare 
Rheum tangaticum
Rheum nobile
Fagopyrum tataricum
Fagopyrum esculentum 
Capsella rubella
Brassica oleracea
Arabidopsis lyrata
Arabis alpina
Thlaspi arvense
Rosa rugosa
Prunus persica
Malus sylvestris
Pyrus bretschneideri
Fragaria vesca 
Argentina anserina
Dryas octopetala
Draba nivalis
Oxyria digyna
Cochlearia groenlandica
